### PR TITLE
Rename pointer to value

### PR DESCRIPTION
**Pull request by mathiasrw**
This change is [Reviewable](https://reviewable.io/reviews/bitcoineler/d/4)

### CODE REVIEW

**Comment by bitcoineler** [comment]
as we discussed in the slack that's ok.

**Comment by mathiasrw** [comment]
Great. Its added.

**Comment by mathiasrw** [comment]
Ok - have a look. I added `tx` to indicate that pointer is to the same transaction letting a delete be an update with a type set to `NULL`.

How do you feel about that?

**Comment by mathiasrw** [comment]
Hmm. you are right. 

But I do think that if its piped on a B we should state that reference is ignored (so you cant make a D piped on a B and refer another transaction

**Pull request merged**
